auto: true

highlighter: rouge
markdown: kramdown
  

pygments: true
paginate: 8
permalink: /:title

title: amar37.github.io
url: http://amar37.github.io
feed: /atom.xml
author_info: <a href="http://amar37.github.io/">Amar</a>
